In [2]:
import numpy as np
import matplotlib.pyplot as plt
from IPython.display import display, Math, Latex
import seaborn as sns
%matplotlib inline

__Задание 1__

Чтобы исследовать на сходимость необходимо определить выражается ли хотя бы один из векторов через другой(-ие). 

a) $A  = \begin{pmatrix}
a_{11} & a_{12} \\ 
a_{21} & a_{22} \\  
a_{31} & a_{32} \\ 
a_{41} & a_{42} \\ 
\end{pmatrix} B  = \begin{pmatrix}
b_{11} & b_{12} \\ 
b_{21} & b_{22} \\  
b_{31} & b_{32} \\ 
b_{41} & b_{42} \\ 
\end{pmatrix}, $ AB и BA не существует, согласно правилу __необходимо, чтобы число столбцов матрицы первого множителя было равно числу строк матрицы второго множителя.__

б) $A  = \begin{pmatrix}
a_{11} & a_{12} & a_{13} & a_{14} & a_{15}\\ 
a_{21} & a_{22} & a_{23} & a_{24} & a_{25}\\ 
\end{pmatrix} B  = \begin{pmatrix}
b_{11} & b_{12} & b_{13} \\ 
b_{21} & b_{22} & b_{23}\\  
b_{31} & b_{32} & b_{33}\\ 
b_{41} & b_{42} & b_{43}\\ 
b_{51} & b_{52} & b_{53}\\ 
\end{pmatrix}, $ BA не существует, согласно правилу __необходимо, чтобы число столбцов матрицы первого множителя было равно числу строк матрицы второго множителя.__ Но произведение AB существует и равно:

$AB  = \begin{pmatrix}
a_{11}*b_{11} + a_{12}*b_{21} + a_{13}*b_{31} + a_{14}*b_{41} + a_{15}*b_{51} & a_{11}*b_{12} + a_{12}*b_{22} + a_{13}*b_{32} + a_{14}*b_{42} + a_{15}*b_{52} & a_{11}*b_{13} + a_{12}*b_{23} + a_{13}*b_{33} + a_{14}*b_{43} + a_{15}*b_{53} \\ 
a_{21}*b_{11} + a_{22}*b_{21} + a_{23}*b_{31} + a_{24}*b_{41} + a_{25}*b_{51} & a_{21}*b_{12} + a_{22}*b_{22} + a_{23}*b_{32} + a_{24}*b_{42} + a_{25}*b_{52} & a_{21}*b_{13} + a_{22}*b_{23} + a_{23}*b_{33} + a_{24}*b_{43} + a_{25}*b_{53}\\ 
\end{pmatrix} $

размерность матрицы AB 2х3

в) $A  = \begin{pmatrix}
a_{11} & a_{12} & a_{13}\\ 
a_{21} & a_{22} & a_{23}\\
a_{31} & a_{32} & a_{33}\\ 
a_{41} & a_{42} & a_{43}\\ 
a_{51} & a_{52} & a_{53}\\ 
a_{61} & a_{62} & a_{63}\\ 
a_{71} & a_{72} & a_{73}\\ 
a_{81} & a_{82} & a_{83}\\ 
\end{pmatrix} B  = \begin{pmatrix}
b_{11} & b_{12} & b_{13} & b_{14} & b_{15} & b_{16} & b_{17} & b_{18}\\ 
b_{21} & b_{22} & b_{23} & b_{24} & b_{25} & b_{26} & b_{27} & b_{28}\\ 
b_{31} & b_{32} & b_{33} & b_{34} & b_{35} & b_{36} & b_{37} & b_{38}\\ 
\end{pmatrix} $ Оба произведения существуют, размерности AB 8x8 и BA 3x3.

г) Оба произведения существуют, размерности АВ и BA 4х4

__Задание 2__

Найдем сумму матриц $A=\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$ и $B=\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}$

$A+B=\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}+
\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}=
\begin{pmatrix}
1 + 4 & -2 -1\\ 
3 + 0 & 0 + 5
\end{pmatrix}= 
\begin{pmatrix}
5 & -3\\ 
3 &  5
\end{pmatrix}$

Найдем произведение матриц A и B:

$AB=\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}
* 
\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}=
\begin{pmatrix}
1* 4 + -2* 0 & 1* (-1) -2* 5 \\ 
3* 4 + 0* 0 & 3* (-1) + 0* 5
\end{pmatrix} 
=\begin{pmatrix}
4 & -11\\ 
12 & -3
\end{pmatrix}$

In [6]:
A = np.array([[1, -2], [3, 0]])
B = np.array([[4, -1], [0, 5]])
print(f'Матрица A\n{A}')
print(f'Матрица B\n{B}')
print(f'Матрица A + B\n{A + B}')
print(f'Матрица AB\n{np.dot(A, B)}')

Матрица A
[[ 1 -2]
 [ 3  0]]
Матрица B
[[ 4 -1]
 [ 0  5]]
Матрица A + B
[[ 5 -3]
 [ 3  5]]
Матрица AB
[[  4 -11]
 [ 12  -3]]


__Задание 3__

Вычислить линейную комбинацию $3A-2B+4C$ для матриц 
$A=\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix}$, $B=\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}$, $C=\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix}.$

$3A-2B+4C=
3\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix}-
2\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}+
4\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix}=
\begin{pmatrix}
3 & 21\\ 
9 & -18\\
\end{pmatrix}+
\begin{pmatrix}
0 & -10\\ 
-4 & 2\\
\end{pmatrix}+
\begin{pmatrix}
8 & -16\\ 
4 & 4\\
\end{pmatrix}=
\begin{pmatrix}
3+0+8 & 21-10-16\\ 
9-4+4 & -18+2+4\\
\end{pmatrix}=
\begin{pmatrix}
11 & -5\\ 
9 & -12
\end{pmatrix}$

In [5]:
A = np.array([[1, 7], [3, -6]])
B = np.array([[0, 5], [2, -1]])
C = np.array([[2, -4], [1, 1]])
print(f'Матрица 3A−2B+4C\n{3 * A - 2 * B + 4 * C}')

Матрица 3A−2B+4C
[[ 11  -5]
 [  9 -12]]


__Задание 4__ 

$A=\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}$

Вычислить $AA^{T}$ и $A^{T}A$.

In [7]:
A = np.array([[4, 1], [5, -2], [2, 3]])
print(f'Матрица:\n{A}')
print(f'Транспонированная матрица:\n{A.T}')
print(f'Матрица A*At\n{np.dot(A,A.T)}')
print(f'Матрица At*A\n{np.dot(A.T,A)}')

Матрица:
[[ 4  1]
 [ 5 -2]
 [ 2  3]]
Транспонированная матрица:
[[ 4  5  2]
 [ 1 -2  3]]
Матрица A*At
[[17 18 11]
 [18 29  4]
 [11  4 13]]
Матрица At*A
[[45  0]
 [ 0 14]]
