**Задание 1**. Решить систему уравнений методом Гаусса:
$\begin{cases}
x_{1}+x_{2}-x_{3}-2x_{4}=0, \\
2x_{1}+x_{2}-x_{3}+x_{4}=-2, \\
x_{1}+x_{2}-3x_{3}+x_{4}=4.
\end{cases}$

**Решение**

Запишем расширенную матрицу системы:

$\left.\begin{pmatrix}
\left.\begin{matrix}
1 & 1 & -1 & -2 \\ 
2 & 1 & -1 & 1 \\ 
1 & 1 & -3 & 1
\end{matrix}\right|
\begin{matrix}
0\\ 
-2\\
4
\end{matrix}
\end{pmatrix}\right|\begin{matrix}
\text{*2 (1)}\\ 
\text{вычитаем из 2-й строки 1-ю}\\
{}
\end{matrix}$ 

$\left.\begin{pmatrix}
\left.\begin{matrix}
1 & 1 & -1 & -2 \\ 
0 & -1 & 1 & -3 \\ 
1 & 1 & -3 & 1
\end{matrix}\right|
\begin{matrix}
0\\ 
-2\\
4
\end{matrix}
\end{pmatrix}\right|\begin{matrix}
{}\\ 
{}\\
\text{вычитаем из 3-й строки 1-ю}
\end{matrix}$

$\begin{pmatrix}
\left.\begin{matrix}
1 & 1 & -1 & -2 \\ 
0 & -1 & 1 & -3 \\ 
0 & 0 & -2 & 3
\end{matrix}\right|
\begin{matrix}
0\\ 
-2\\
4
\end{matrix}
\end{pmatrix}$

Cистема будет иметь множество решений:

$x_4 = C$

$x_3 = -\frac{4-3C}{2}$

$x_2 = 2-\frac{4-3C}{2}-3C$

$x_1 = -2+\frac{4-3C}{2}+3C-\frac{4-3C}{2}+2C = 5C-2$

**Задание 2**. Проверить на совместность и выяснить, сколько решений будет иметь система линейных уравнений:

   а) $\begin{cases}
3x_{1}-x_{2}+x_{3}=4, \\
2x_{1}-5x_{2}-3x_{3}=-17, \\
x_{1}+x_{2}-x_{3}=0;
\end{cases}$
    
   б) $\begin{cases}
2x_{1}-4x_{2}+6x_{3}=1, \\
x_{1}-2x_{2}+3x_{3}=-2, \\
3x_{1}-6x_{2}+9x_{3}=5;
\end{cases}$
    
   в) $\begin{cases}
x_{1}+2x_{2}+5x_{3}=4, \\
3x_{1}+x_{2}-8x_{3}=-2. 
\end{cases}$

In [12]:
import numpy as np

def compare_rank(A, b):
    A_ext = np.column_stack([A, b])
    rank_A = np.linalg.matrix_rank(A)
    rank_A_ext = np.linalg.matrix_rank(A_ext)
    n = len(A[0])

    print(f'A:\n{A}\n')
    print(f'A_ext:\n{A_ext}\n')
    print(f'rank(A): {rank_A}\n')
    print(f'rank(A_ext): {rank_A_ext}\n')
    print(f'# of vars: {n}\n')

    if rank_A == rank_A_ext == n:
        print(f'Система совместна и имеет единственное решение.\n')
    elif rank_A == rank_A_ext < n:
        print(f'Система совместна и имеет бесконечное кол-во решений.\n')
    elif rank_A < rank_A_ext:
        print(f'Система несовместна.\n')

In [13]:
print("a)")
A = np.array([[3, -1, 1], [2, -5, -3], [1, 1, -1]])
b = np.array([4, -17, 0])
compare_rank(A, b)

print("б)")
A = np.array([[2, -4, 6], [1, -2, 3], [3, -6, 9]])
b = np.array([1, -2, 5])
compare_rank(A,b)

print("в)")
A = np.array([[1, 2, 5], [3, 1, -8]])
b = np.array([4, -2])
compare_rank(A,b)

a)
A:
[[ 3 -1  1]
 [ 2 -5 -3]
 [ 1  1 -1]]

A_ext:
[[  3  -1   1   4]
 [  2  -5  -3 -17]
 [  1   1  -1   0]]

rank(A): 3

rank(A_ext): 3

# of vars: 3

Система совместна и имеет единственное решение.

б)
A:
[[ 2 -4  6]
 [ 1 -2  3]
 [ 3 -6  9]]

A_ext:
[[ 2 -4  6  1]
 [ 1 -2  3 -2]
 [ 3 -6  9  5]]

rank(A): 1

rank(A_ext): 2

# of vars: 3

Система несовместна.

в)
A:
[[ 1  2  5]
 [ 3  1 -8]]

A_ext:
[[ 1  2  5  4]
 [ 3  1 -8 -2]]

rank(A): 2

rank(A_ext): 2

# of vars: 3

Система совместна и имеет бесконечное кол-во решений.



**Задание 3**. Проверить на совместность и выяснить, сколько решений будет иметь система линейных уравнений, заданная расширенной матрицей
$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
1 & 3 & -2 & 4\\ 
0 & 5 & 0 & 1\\ 
0 & 0 & 3 & 0\\ 
0 & 0 & 0 & 2
\end{matrix}\right|
\begin{matrix}
3\\ 
2\\
4\\
1
\end{matrix}
\end{pmatrix}$

In [16]:
A = np.array([[1, 3, -2, 4], [0, 5, 0, 1], [0, 0, 3, 0], [0, 0, 0, 2]])
b = np.array([3, 2, 4, 1])
compare_rank(A,b)

A:
[[ 1  3 -2  4]
 [ 0  5  0  1]
 [ 0  0  3  0]
 [ 0  0  0  2]]

A_ext:
[[ 1  3 -2  4  3]
 [ 0  5  0  1  2]
 [ 0  0  3  0  4]
 [ 0  0  0  2  1]]

rank(A): 4

rank(A_ext): 4

# of vars: 4

Система совместна и имеет единственное решение.



$x_4=\frac{1}{2}$

$x_3=\frac{4}{3}$

$x_2=\frac{2-\frac{1}{2}}{5} = 0.3$

$x_1=3-\frac{2-\frac{1}{2}}{5}+\frac{4}{3}-\frac{1}{2} = 3.5$

**Задание 4**. Дана система линейных уравнений, заданная расширенной матрицей

$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{matrix}\right|
\begin{matrix}
a\\ 
b\\
c
\end{matrix}
\end{pmatrix}$

Найти соотношение между параметрами $a$, $b$ и $c$, при которых система является несовместной.

Запишем систему в виде расширенной матрицы.
$\left.\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3 \\ 
4 & 5 & 6 \\ 
7 & 8 & 9
\end{matrix}\right|
\begin{matrix}
a\\ 
b\\
c
\end{matrix}
\end{pmatrix}\right|\begin{matrix}
\text{*2 и вычитаем из 2-ой и 3-ей}\\ 
{}\\
{}
\end{matrix}$ = 
$\left.\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3 \\ 
2 & 1 & 0 \\ 
4 & 2 & 0
\end{matrix}\right|
\begin{matrix}
a\\ 
b - 2a\\
c - 3a
\end{matrix}
\end{pmatrix}\right|\begin{matrix}
{}\\ 
\text{*2 и вычитаем из 3-ей}\\
{}
\end{matrix}$ = 
$\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3 \\ 
2 & 1 & 0 \\ 
0 & 0 & 0
\end{matrix}\right|
\begin{matrix}
a\\ 
b - 2a\\
c + a - 2b
\end{matrix}
\end{pmatrix}$

Если $c + a - 2b \neq 0$, то система несовместна.

**Задание 5** *.Написать на Python программу с реализацией одного из изученных алгоритмов решения СЛАУ.

In [26]:
# Метод Крамера
import copy

def kramer(A, b):
    detA = np.linalg.det(A)

    print(f'A:\n{A}\n')
    print(f'b:\n{b}\n')

    print(f'det(A): {detA}\n')
    #проверим совместность системы
    if detA != 0:
        print(f'Система совместна и имеет единственное решение\n')
        k = 0
        Ds = []
        #соберем лист определителей с подмененым столбцом
        while k != len(A):
            tmpD = []
            for i,line in enumerate(A):
                tmpD.append(copy.deepcopy(line))
                tmpD[i][k] = b[i]
            Ds.append(copy.deepcopy(tmpD))
            k+=1

        print(Ds)
        #считаем det для каждого определителя из предыдущего списка
        p = [np.linalg.det(np.array(i)) for i in Ds]
        #находим x-сы
        Xs = [i/detA for i in p]
        for i,x in enumerate(Xs):
            print(f'x{i} = {x}\n')            
    else:
        print(f'Cистема  несовместна\n')

**Задание 1**. Решить систему уравнений методом Крамера:

   а) $\begin{cases}
x_{1}-2x_{2}=1 \\
3x_{1}-4x_{2}=7
\end{cases}$
    
   б) $\begin{cases}
2x_{1}-x_{2}+5x_{3}=10 \\
x_{1}+x_{2}-3x_{3}=-2 \\
2x_{1}+4x_{2}+x_{3}=1
\end{cases}$

In [27]:
print('a)')
A = np.array([[1, -2], [3, -4]])
b = np.array([1, 7])
kramer(A,b)

a)
A:
[[ 1 -2]
 [ 3 -4]]

b:
[1 7]

det(A): 2.0000000000000004

Система совместна и имеет единственное решение

[[array([ 1, -2]), array([ 7, -4])], [array([1, 1]), array([3, 7])]]
x0 = 4.999999999999998

x1 = 1.9999999999999996



In [28]:
print('b)')
A = np.array([[2, -1, 5], [1, 1, -3], [2, 4, 1]])
b = np.array([10, -2, 1])
kramer(A,b)

b)
A:
[[ 2 -1  5]
 [ 1  1 -3]
 [ 2  4  1]]

b:
[10 -2  1]

det(A): 42.99999999999998

Система совместна и имеет единственное решение

[[array([10, -1,  5]), array([-2,  1, -3]), array([1, 4, 1])], [array([ 2, 10,  5]), array([ 1, -2, -3]), array([2, 1, 1])], [array([ 2, -1, 10]), array([ 1,  1, -2]), array([2, 4, 1])]]
x0 = 2.0000000000000018

x1 = -1.0000000000000009

x2 = 1.0



**Задание 2.** Найти $L$-матрицу $LU$-разложения для матрицы коэффициентов:

   а)$\begin{pmatrix}
1 & 2 & 4 \\ 
2 & 9 & 12 \\ 
3 & 26 & 30
\end{pmatrix}$
    
   б)$\begin{pmatrix}
1 & 1 & 2 & 4\\ 
2 & 5 & 8 & 9\\ 
3 & 18 & 29 & 18\\
4 & 22 & 53 & 33
\end{pmatrix}$

**Решение**

а) Матрица коэффициентов:

$\begin{pmatrix}
1 & 2 & 4 \\ 
2 & 9 & 12 \\ 
3 & 26 & 30
\end{pmatrix}$

Умножим 1 строку на 2 и вычтем из 2 строки:

U:<br>

$\begin{pmatrix}
1 & 2 & 4 \\ 
0 & 5 & 4 \\ 
3 & 26 & 30
\end{pmatrix}$

L:

$\begin{pmatrix}
1 & 0 & 0 \\ 
2 & 1 & 0 \\ 
I_{31} & I_{32} & 1
\end{pmatrix}$

Умножим 1 строку на 3 и вычтем из 3 строки:

Матрица U:

$\begin{pmatrix}
1 & 2 & 4 \\ 
0 & 5 & 4 \\ 
0 & 20 & 18
\end{pmatrix}$

Матрица L:

$\begin{pmatrix}
1 & 0 & 0 \\ 
2 & 1 & 0 \\ 
3 & I_{32} & 1
\end{pmatrix}$

Умножим 2 строку на 4 и вычтем из 3 строки:

Матрица U:

$\begin{pmatrix}
1 & 2 & 4 \\ 
0 & 5 & 4 \\ 
0 & 0 & 2
\end{pmatrix}$

Матрица L:

$\begin{pmatrix}
1 & 0 & 0 \\ 
2 & 1 & 0 \\ 
3 & 4 & 1
\end{pmatrix}$

б) Матрица коэффициентов:

$\begin{pmatrix}
1 & 1 & 2 & 4 \\ 
2 & 5 & 8 & 9 \\ 
3 & 18 & 29 & 18 \\
4 & 22 & 53 & 33
\end{pmatrix}$

Умножим 1 строку на 2 и вычтем из 2 строки:

Матрица U:

$\begin{pmatrix}
1 & 1 & 2 & 4 \\ 
0 & 3 & 4 & 1 \\ 
3 & 18 & 29 & 18 \\
4 & 22 & 53 & 33
\end{pmatrix}$

Матрица L:

$\begin{pmatrix}
1 & 0 & 0 & 0 \\ 
2 & 1 & 0 & 0 \\ 
I_{31} & I_{32} & 1 & 0 \\
I_{41} & I_{42} & I_{43} & 1
\end{pmatrix}$

Умножим 1 строку на 3 и вычтем из 3 строки:

Матрица U:

$\begin{pmatrix}
1 & 1 & 2 & 4 \\ 
0 & 3 & 4 & 1 \\ 
0 & 15 & 23 & 6 \\
4 & 22 & 53 & 33
\end{pmatrix}$

Матрица L:

$\begin{pmatrix}
1 & 0 & 0 & 0 \\ 
2 & 1 & 0 & 0 \\ 
3 & I_{32} & 1 & 0 \\
I_{41} & I_{42} & I_{43} & 1
\end{pmatrix}$

Умножим 1 строку на 4 и вычтем из 4 строки:

Матрица U:

$\begin{pmatrix}
1 & 1 & 2 & 4 \\ 
0 & 3 & 4 & 1 \\ 
0 & 15 & 23 & 6 \\
0 & 18 & 45 & 17
\end{pmatrix}$

Матрица L:

$\begin{pmatrix}
1 & 0 & 0 & 0 \\ 
2 & 1 & 0 & 0 \\ 
3 & I_{32} & 1 & 0 \\
4 & I_{42} & I_{43} & 1
\end{pmatrix}$

Умножим 2 строку на 5 и вычтем из 3 строки:

Матрица U:

$\begin{pmatrix}
1 & 1 & 2 & 4 \\ 
0 & 3 & 4 & 1 \\ 
0 & 0 & 3 & 1 \\
0 & 18 & 45 & 17
\end{pmatrix}$

Матрица L:

$\begin{pmatrix}
1 & 0 & 0 & 0 \\ 
2 & 1 & 0 & 0 \\ 
3 & 5 & 1 & 0 \\
4 & I_{42} & I_{43} & 1
\end{pmatrix}$

Умножим 2 строку на 6 и вычтем из 4 строки:

Матрица U:

$\begin{pmatrix}
1 & 1 & 2 & 4 \\ 
0 & 3 & 4 & 1 \\ 
0 & 0 & 3 & 1 \\
0 & 0 & 21 & 11
\end{pmatrix}$

Матрица L:

$\begin{pmatrix}
1 & 0 & 0 & 0 \\ 
2 & 1 & 0 & 0 \\ 
3 & 5 & 1 & 0 \\
4 & 6 & I_{43} & 1
\end{pmatrix}$

Умножим 3 строку на 7 и вычтем из 4 строки:

Матрица U:

$\begin{pmatrix}
1 & 1 & 2 & 4 \\ 
0 & 3 & 4 & 1 \\ 
0 & 0 & 3 & 1 \\
0 & 0 & 0 & 4
\end{pmatrix}$

Матрица L:

$\begin{pmatrix}
1 & 0 & 0 & 0 \\ 
2 & 1 & 0 & 0 \\ 
3 & 5 & 1 & 0 \\
4 & 6 & 7 & 1
\end{pmatrix}$

**Задание 3.** Решить систему линейных уравнений методом $LU$-разложения

$\begin{cases}
2x_{1}+x_{2}+3x_{3}=1 \\
11x_{1}+7x_{2}+5x_{3}=-6 \\
9x_{1}+8x_{2}+4x_{3}=-5
\end{cases}$

**Решение**

$\begin{pmatrix}
\left.\begin{matrix}
2 & 1 & 3\\ 
11 & 7 & 5\\ 
9 & 8 & 4
\end{matrix}
\right|\begin{matrix}
1\\ 
-6\\
-5
\end{matrix}
\end{pmatrix}
\,\,\,\,\,\Rightarrow \,\,\,\,\,
\begin{pmatrix}
\left.\begin{matrix}
2 & 1 & 3\\ 
22 & 14 & 10\\ 
18 & 16 & 8
\end{matrix}\right|
\begin{matrix}
1\\ 
-12\\
-10
\end{matrix}
\end{pmatrix}$

$\begin{pmatrix}
2 & 1 & 3 \\ 
22 & 14 & 10 \\ 
18 & 16 & 8
\end{pmatrix} 
\,\,\,\,\,\Rightarrow \,\,\,\,\,
\begin{pmatrix}
2 & 1 & 3 \\ 
0 & 3 & -23 \\ 
0 & 7 & -19
\end{pmatrix}
\,\,\,\,\,\Rightarrow \,\,\,\,\,
\begin{pmatrix}
2 & 1 & 3 \\ 
0 & 3 & -23 \\ 
0 & 0 & \frac{104}{3}
\end{pmatrix}=U$
$\begin{pmatrix}
1 & 0 & 0 \\ 
l_{21} & 1 & 0 \\ 
l_{31} & l_{32} & 1
\end{pmatrix} 
\,\,\,\,\,\Rightarrow \,\,\,\,\,
\begin{pmatrix}
1 & 0 & 0 \\ 
11 & 1 & 0 \\ 
9 & l_{32} & 1
\end{pmatrix}
\,\,\,\,\,\Rightarrow \,\,\,\,\,
\begin{pmatrix}
1 & 0 & 0 \\ 
11 & 1 & 0 \\ 
9 & \frac{7}{3} & 1
\end{pmatrix}=L$

Решим систему $Ly=b$:

$\begin{cases}
y_1=1 \\
11y_{1}+y_2=-12 \\
9y_{1}+\frac{7}{3}y_{2}+y_{3}=-10
\end{cases}
\,\,\,\,\,\Rightarrow \,\,\,\,\,
\begin{cases}
y_1=1 \\
y_2=-23 \\
y_{3}=\frac{104}{3}
\end{cases}$

Решим систему $Ux=y$:

$\begin{cases}
2x_1+x_2+3x_3=1 \\
3x_2-23x_3=-23 \\
\frac{104}{3}x_3=\frac{104}{3}
\end{cases}
\,\,\,\,\,\Rightarrow \,\,\,\,\,
\begin{cases}
x_1=-1 \\
x_2=0 \\
x_3=1
\end{cases}$

Ответ: $(-1,0,1)$

**Задание 4.** Решить систему линейных уравнений методом Холецкого

$\begin{cases}
81x_{1}-45x_{2}+45x_{3}=531 \\
-45x_{1}+50x_{2}-15x_{3}=-460 \\
45x_{1}-15x_{2}+38x_{3}=193
\end{cases}$

**Решение**

$l_{11}=\sqrt{a_{11}}=\sqrt{81}=9,$

$l_{21}=\frac{a_{21}}{l_{11}}=\frac{-45}{9}=-5,$

$l_{31}=\frac{a_{31}}{l_{11}}=\frac{45}{9}=5,$

$l_{22}=\sqrt{a_{22}-l_{21}^{2}}=\sqrt{50 - 25}=\sqrt{25}=5,$

$l_{32}=\frac{1}{l_{22}}\left ( a_{32}-l_{21}l_{31} \right)=\frac{1}{5}(-15+25)=\frac{10}{5}=2,$

$l_{33}=\sqrt{a_{33}-l_{31}^{2}-l_{32}^{2}}=\sqrt{38-25-4}=\sqrt{9}=3.$

Получили матрицу 

$L = \begin{pmatrix}
9 & 0 & 0 \\ 
-5 & 5 & 0 \\ 
5 & 2 & 3
\end{pmatrix}, 
\; \;
L^{T} = \begin{pmatrix}
9 & -5 & 5 \\ 
0 & 5 & 2 \\ 
0 & 0 & 3
\end{pmatrix}.$

$\begin{cases}
9y_1=531, \\
-5y_1+5y_2=-460, \\
5y_1+2y_2+3y_3=193.
\end{cases} 
\,\,\,\,\,\Rightarrow \,\,\,\,\,
\begin{cases}
y_1=59, \\
y_2=-33, \\
y_3=-12.
\end{cases}$

$\begin{cases}
9x_1-5x_2+5x_3=59, \\
5x_2+2x_3=-33, \\
3x_{3}=-12.
\end{cases}
\,\,\,\,\,\Rightarrow \,\,\,\,\,
\begin{cases}
x_1=6, \\
x_2=-5, \\
x_3=-4.
\end{cases}$

Ответ: $(6,-5,-4)$